version: '3.8'
services:
  template-lapis:
    container_name: template-lapis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LAPIS_TYPE: "lua"
    ports:
      - "7000:8080"
